### ISSUE TITLE
How can i Change we Thunder Sound?? 

### ISSUE THREAD

**Issue by DragonfireHD** [cyphr3x/Weather#1]
Can you me help?
How can i Change we Thunder Sound

**Comment by cyphr3x** [comment]
There is no way to change the sound. You can only disable it.

**Comment by DragonfireHD** [comment]
But the sound off the thunde is not Quality pls fix the sound

**Comment by cyphr3x** [comment]
Don’t use the plugin.

**Comment by DragonfireHD** [comment]
Why I don't use them??

**Comment by DragonfireHD** [comment]
I say your Problems and you say don't use the Plugin
